### ISSUE TITLE
卡到99.99%不动了

### ISSUE THREAD

**Issue by zhenghan123** [liusj5257/AzurLaneLuaScripts_AdjustJPToCN#26]
![image](https://github.com/liusj5257/AzurLaneLuaScripts_AdjustJPToCN/assets/61129862/c4b22ab0-569f-4849-b30c-89fbde3f02e8)
跟着教程走，就卡到这里了。
用的mumu12模拟器

**Comment by liusj5257** [comment]
不是本仓库资源的原因
